name: build
on: [push]
    
jobs:
  build-linux:
    name: Build Android & Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout git repo
      - uses: actions/checkout@v2.4.2
      
      # Setup Java environment in order to build the Android app.
      - uses: actions/setup-java@v3.5.0
        with:
          java-version: '12.x'
      
      # setup linux environment
      - name: Setup Linux
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
      
      # Get flutter dependencies.
      - run: flutter pub get
      
      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .
      
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings .
      
      # Run widget tests for our flutter project.
      #- run: flutter test
      
      # Build apk.
      - name: Build Android
        run: flutter build apk
      # Build linux
      - name: Build Linux
        run: |
          flutter config --enable-linux-desktop
          flutter build linux
      
      # Upload generated binaries
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      
      - uses: actions/upload-artifact@v3
        with:
          name: release-linux
          path: build/linux/release/bundle/
          
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:      
      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
      
      # Get flutter dependencies.
      - run: flutter pub get
      
      # Build windows
      - run: |
          flutter config --enable-windows-desktop
          flutter build windows
      
      # Upload generated binaries
      - uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: build/windows/runner/release/
